# Working directory (set to project root)
root = "."

# Temporary directory for builds (defaults to ./tmp)
tmp_dir = "tmp"

[build]
  # Build command using go build with output to temporary directory
  cmd = "go build -o ./tmp/event-bookie ./cmd/event-bookie/main.go"

  # Include all go files and exclude test files
  include_ext = ["go"]
  exclude_regex = ["_test\\.go"]

  # Watch all directories within the project (except for some specific ones)
  include_dir = ["./", "config/", "internal/", "pkg/", "router/"]
  exclude_dir = ["docs/", "migrations/", "tests/"]

