basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: This is a sample server for event booking.
  title: Event Booking API
  version: "1.0"
paths: {}
swagger: "2.0"
