openapi: 3.0.0
info:
  title: Event Bookie API
  description: API for managing events, users, registrations, etc.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /events:
    get:
      summary: Retrieve all events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        location:
          type: string
        dateTime:
          type: string
      required:
        - name
        - description
        - location
        - dateTime
    EventInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        location:
          type: string
        dateTime:
          type: string
      required:
        - name
        - description
        - location
        - dateTime
