openapi: 3.0.0
info:
  title: Event Bookie API
  version: 1.0.0
  description: API documentation for the Event Bookie application.

servers:
  - url: http://localhost:8080/api/v1

paths:
  # Define your API paths and operations here
  # ...

components:
  schemas:
    # Define your data models and schemas here
    # ...

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT