openapi: 3.0.0
info:
  title: Event Booking API
  description: API documentation for the Event Booking application
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /events:
    get:
      summary: Get all events
      description: Retrieve a list of all events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Create a new event
      description: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewEvent'
      responses:
        '201':
          description: The created event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        date:
          type: string
          format: date
        venue:
          type: string
        organizer:
          type: string
      required:
        - name
        - date
        - venue
        - organizer
    NewEvent:
      type: object
      properties:
        name:
          type: string
        date:
          type: string
          format: date
        venue:
          type: string
        organizer:
          type: string
      required:
        - name
        - date
        - venue
        - organizer
