openapi: 3.0.0
info:
  title: Event Bookie API
  description: API documentation for the Event Bookie application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /events:
    get:
      summary: Retrieve all events
      responses:
        '200':
          description: A list of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '201':
          description: Event created successfully
        '400':
          description: Bad request
  /events/{id}:
    get:
      summary: Retrieve an event by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the event to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        date:
          type: string
          format: date
        location:
          type: string
