create table "public"."booking" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."booking" enable row level security;

CREATE UNIQUE INDEX booking_pkey ON public.booking USING btree (id);

alter table "public"."booking" add constraint "booking_pkey" PRIMARY KEY using index "booking_pkey";

grant delete on table "public"."booking" to "anon";

grant insert on table "public"."booking" to "anon";

grant references on table "public"."booking" to "anon";

grant select on table "public"."booking" to "anon";

grant trigger on table "public"."booking" to "anon";

grant truncate on table "public"."booking" to "anon";

grant update on table "public"."booking" to "anon";

grant delete on table "public"."booking" to "authenticated";

grant insert on table "public"."booking" to "authenticated";

grant references on table "public"."booking" to "authenticated";

grant select on table "public"."booking" to "authenticated";

grant trigger on table "public"."booking" to "authenticated";

grant truncate on table "public"."booking" to "authenticated";

grant update on table "public"."booking" to "authenticated";

grant delete on table "public"."booking" to "service_role";

grant insert on table "public"."booking" to "service_role";

grant references on table "public"."booking" to "service_role";

grant select on table "public"."booking" to "service_role";

grant trigger on table "public"."booking" to "service_role";

grant truncate on table "public"."booking" to "service_role";

grant update on table "public"."booking" to "service_role";


